server:
  port: 8080

spring:
  application:
    name: e-museum
  datasource:
    url: jdbc:mysql://localhost:3308/e-museum?createDatabaseIfNotExist=true
    username: root
    password: 54321
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
  servlet:
    multipart:
        max-file-size: 20MB
        max-request-size: 20MB
  mvc:
    async:
      request-timeout: 300000 # timeout long nécessaire pour le téléchargement de fichiers lourds dans les requetes HTTP
